name: Build And Push 
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  cicd:
    uses: ClipMX/cicd/.github/workflows/build-and-push.yml@main
    secrets: inherit # pass all secrets
    with:
      image_name: "service-ts-c3-onboarding"
      integration_tests_cmd: "make cicd-integration-test"
      coverage: true
      coverage-threshold: 80
      cache-key-hash-files: "**/package.json"
      cache-path: |
        node-modules-cache
      cache-map: |
        {
          "node-modules-cache": "/home/root/.npm"
        }
