name: Update Version on Tag Push

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write  # Needed to push commits and tags
  actions: read    # Needed to read workflow files
  pull-requests: write  # Needed to create pull requests

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: ${{ github.event.repository.default_branch }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Extract tag name
        id: tag_name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          CLEAN_VERSION=${TAG_NAME#v}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "clean_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
          echo "Original tag: $TAG_NAME"
          echo "Clean version: $CLEAN_VERSION"
      
      - name: Update version in package.json
        run: |
          echo "Current package.json version:"
          cat package.json | grep '"version"'
          echo "Tag name: ${{ steps.tag_name.outputs.tag_name }}"
          echo "Clean version: ${{ steps.tag_name.outputs.clean_version }}"
          
          # Use the existing script to update version
          node ./scripts/update-version-tag.js "${{ steps.tag_name.outputs.tag_name }}"
          
          echo "Updated package.json version:"
          cat package.json | grep '"version"'
      
      - name: Create branch and commit
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the updated package.json
          git add package.json
          
          # Create a new branch
          BRANCH_NAME="update-version-${{ steps.tag_name.outputs.clean_version }}"
          echo "Creating branch: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          
          # Create commit
          git commit -m "chore: update version in package.json to ${{ steps.tag_name.outputs.clean_version }}"
          
          # Push the branch
          git push origin $BRANCH_NAME
          
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Successfully created branch $BRANCH_NAME"
        id: commit_changes
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: ${{ steps.commit_changes.outputs.branch_name }}
          base: ${{ github.event.repository.default_branch }}
          title: "chore: update version to ${{ steps.tag_name.outputs.clean_version }}"
          body: |
            This PR updates the version in package.json to ${{ steps.tag_name.outputs.clean_version }}
            
            **Changes:**
            - Updated version in package.json from previous version to ${{ steps.tag_name.outputs.clean_version }}
            
            **Triggered by:** Tag push `${{ steps.tag_name.outputs.tag_name }}`
          labels: |
            version-update
            automated
          delete-branch: true
